### ISSUE TITLE
problem to run the code

### ISSUE THREAD

**Issue by TGanor** [ChristophRaab/rrslvq#2]
when i try to run the demo i get 
Failed to import SciKit-Multiflow!
Traceback (most recent call last):
  File "rrslvq.py", line 58, in <module>
    class RRSLVQ(ClassifierMixin, skmultiflow.core.base.StreamModel, BaseEstimator):
NameError: name 'skmultiflow' is not defined

the problem is that i can not run the following command
from skmultiflow.core.base import StreamModel

**Comment by ChristophRaab** [comment]
Thank you for pointing out the error.

I have updatet the code to the latest multiflow version to fix the error.
See latest commit: [https://github.com/ChristophRaab/rrslvq/commit/2cdd53b58c97b03331ba20f18f89d6aef9daacca](url)
