### ISSUE TITLE
not being able to run it on my windows PC

### ISSUE THREAD

**Issue by TGanor** [ChristophRaab/rrslvq#3]
Traceback (most recent call last):
  File "rrslvq.py", line 516, in <module>
    stream = ReoccuringDriftStream(stream=s1, drift_stream=s2,random_state=None,alpha=90.0, position=2000,width=1)
TypeError: Can't instantiate abstract class ReoccuringDriftStream with abstract methods prepare_for_use

**Comment by ChristophRaab** [comment]
I cant reproduce this error. Do you have the latest version of the code and scikit-multiflow?

**Comment by TGanor** [comment]
skmultiflow.__version__ is '0.4.1'

**Comment by TGanor** [comment]
All versions 
IPython 7.12.0
IPython.core.release 7.12.0
PIL 7.0.0
PIL.Image 7.0.0
PIL._version 7.0.0
_csv 1.0
_ctypes 1.1.0
_decimal 1.70
argparse 1.1
attr 19.3.0
backcall 0.1.0
bottleneck 1.3.2
cffi 1.14.0
colorama 0.4.3
csv 1.0
ctypes 1.1.0
cycler 0.10.0
dateutil 2.8.1
decimal 1.70
decorator 4.4.1
distutils 3.7.6
http.server 0.6
idna 2.8
idna.idnadata 11.0.0
idna.package_data 2.8
importlib_metadata 1.5.0
ipykernel 5.1.4
ipykernel._version 5.1.4
ipython_genutils 0.2.0
ipython_genutils._version 0.2.0
ipywidgets 7.5.1
ipywidgets._version 7.5.1
jedi 0.14.1
joblib 0.14.1
joblib.externals.cloudpickle 1.2.2
joblib.externals.loky 2.6.0
json 2.0.9
jsonschema 3.2.0
jupyter_client 5.3.4
jupyter_client._version 5.3.4
jupyter_core 4.6.1
jupyter_core.version 4.6.1
kiwisolver 1.1.0
logging 0.5.1.2
matplotlib 3.1.3
matplotlib.backends.backend_agg 3.1.3
mkl 2.3.0
nbformat 5.0.4
nbformat._version 5.0.4
numpy 1.18.1
numpy.core 1.18.1
numpy.core._multiarray_umath 3.1
numpy.lib 1.18.1
numpy.linalg._umath_linalg b'0.1.5'
pandas 1.0.1
parso 0.5.2
pickleshare 0.7.5
platform 1.0.8
plotly 4.5.4
plotly.version 4.5.4
prompt_toolkit 3.0.3
psutil 5.6.7
pygments 2.5.2
pyparsing 2.4.6
pytz 2019.3
re 2.2.1
scipy 1.4.1
scipy._lib._uarray 0.5.1+5.ga864a57.scipy
scipy._lib.decorator 4.0.5
scipy._lib.six 1.2.0
scipy.integrate._dop b'$Revision: $'
scipy.integrate._ode $Id$
scipy.integrate._odepack  1.9 
scipy.integrate._quadpack  1.13 
scipy.integrate.lsoda b'$Revision: $'
scipy.integrate.vode b'$Revision: $'
scipy.interpolate._fitpack  1.7 
scipy.interpolate.dfitpack b'$Revision: $'
scipy.linalg 0.4.9
scipy.linalg._fblas b'$Revision: $'
scipy.linalg._flapack b'$Revision: $'
scipy.linalg._flinalg b'$Revision: $'
scipy.ndimage 2.0
scipy.optimize._cobyla b'$Revision: $'
scipy.optimize._lbfgsb b'$Revision: $'
scipy.optimize._minpack  1.10 
scipy.optimize._nnls b'$Revision: $'
scipy.optimize._slsqp b'$Revision: $'
scipy.optimize.minpack2 b'$Revision: $'
scipy.sparse.linalg.eigen.arpack._arpack b'$Revision: $'
scipy.sparse.linalg.isolve._iterative b'$Revision: $'
scipy.special.specfun b'$Revision: $'
scipy.stats.mvn b'$Revision: $'
scipy.stats.statlib b'$Revision: $'
six 1.14.0
sklearn 0.22.1
sklearn.base 0.22.1
sklearn.datasets._svmlight_format_io 0.22.1
sklearn.externals._arff 2.4.0
sklearn.utils._joblib 0.14.1
skmultiflow 0.4.1
skmultiflow._version 0.4.1
skmultiflow.core.base 0.4.1
socketserver 0.4
sortedcontainers 2.1.0
traitlets 4.3.3
traitlets._version 4.3.3
urllib.request 3.7
zlib 1.0
zmq 18.1.1
zmq.sugar 18.1.1
zmq.sugar.version 18.1.1

**Comment by ChristophRaab** [comment]
I have identified the error. Please check out the latest commit:  [https://github.com/ChristophRaab/rrslvq/commit/e29a53b0c4a21934b1b8c8cfe1b6bb1c343972b0](url)

Does this solve the issue?

**Comment by TGanor** [comment]
I will try later and let you know

**Comment by TGanor** [comment]
Yes now it is running many thanks 
can you please send some documentation so i will understand what i am seeing

**Comment by TGanor** [comment]
I also see error messages like 
 return  1.0 / (1.0 + np.exp((x)))
 ###################- [95%] [19.09s]C:\Users\tamirg\OneDrive - Nice Systems Ltd\Documents\TG Notebooks\testing\rrslvq-master\ReoccuringDriftStream.py:170: RuntimeWarning: overflow encountered in exp

**Comment by ChristophRaab** [comment]
> 
> 
> I also see error messages like
> return 1.0 / (1.0 + np.exp((x)))
> ###################- [95%] [19.09s]C:\Users\tamirg\OneDrive - Nice Systems Ltd\Documents\TG Notebooks\testing\rrslvq-master\ReoccuringDriftStream.py:170: RuntimeWarning: overflow encountered in exp
This is an runtime warning and bother you further. However, you can supress it by yourself if you like.

**Comment by ChristophRaab** [comment]
> 
> 
> Yes now it is running many thanks
> can you please send some documentation so i will understand what i am seeing

I will add some reasonable documentation to the code, hopefully, till the end of the week and notify you in this thread.

**Comment by ChristophRaab** [comment]
sorry for the late response. I added some documentation. Please let me know if there are any problems with it.
