### ISSUE TITLE
Distinguishing abrupt and gradual drift

### ISSUE THREAD

**Issue by szamani20** [ChristophRaab/rrslvq#4]
I run an implementation of your work based on `skmultiflow` implementation here:
[https://scikit-multiflow.readthedocs.io/en/stable/api/generated/skmultiflow.drift_detection.KSWIN.html](https://scikit-multiflow.readthedocs.io/en/stable/api/generated/skmultiflow.drift_detection.KSWIN.html)

But I couldn't find any way to distinguish between abrupt and gradual drift that you discuss in the paper. Could you please explain whether this feature is implemented or not? Thanks.

**Comment by ChristophRaab** [comment]
Currently, the [ConceptDriftStream ](https://scikit-multiflow.readthedocs.io/en/stable/api/generated/skmultiflow.data.ConceptDriftStream.html#skmultiflow.data.ConceptDriftStream)Class of skmultiflow simulates the abrupt drift. Please see the documentation for more details. 
Further, the skmultiflow package has some gradual drift streams like the [Hyperplane ](https://scikit-multiflow.readthedocs.io/en/stable/api/generated/skmultiflow.data.HyperplaneGenerator.html#skmultiflow.data.HyperplaneGenerator) Generator to simulate this kind of drift. 

To use KSWIN within this setting, you can choose appropriate parameters, as discussed in the paper. For example, a small window size if the rate of drift is assumed to be high. However, there is currently no option to specify kwsin to a certain drift in terms of just selecting the drift it has to deal with.
